name: Build OnePlus SM8550 Kernel

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Free up disk space and setup swap
      run: |
        echo "==> Initial disk usage:"
        df -h
        
        # 删除大型软件包和文件
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /opt/ghc
        sudo rm -rf /opt/hostedtoolcache/CodeQL
        sudo rm -rf /usr/local/share/boost
        sudo rm -rf /usr/local/graalvm/
        sudo rm -rf /usr/local/share/chromium
        sudo rm -rf /usr/local/lib/node_modules
        sudo rm -rf /usr/share/swift
        
        # 清理包管理器缓存
        sudo apt-get clean
        sudo apt-get autoremove -y
        
        # 清理 Docker
        docker system prune -af 2>/dev/null || true
        
        echo "==> After cleanup:"
        df -h

        echo "==> Setting up 16GB swap space..."
        sudo fallocate -l 16G /swapfile
        sudo chmod 600 /swapfile
        sudo mkswap /swapfile
        sudo swapon /swapfile
        sudo swapon --show
        echo "==> Swap setup completed."
        
    - name: Setup build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          bc \
          bison \
          flex \
          libssl-dev \
          libelf-dev \
          zip \
          python3 \
          git \
          dwarves
        
        # 立即清理
        sudo apt-get clean
        
    - name: Create clean workspace
      run: |
        # 创建全新的工作目录，避免 warning
        rm -rf ~/kernel 2>/dev/null || true
        mkdir -p ~/kernel
        cd ~/kernel
        
        echo "WORK_DIR=$HOME/kernel" >> $GITHUB_ENV
        echo "==> Workspace created at: $HOME/kernel"
        
    - name: Clone clang toolchain
      run: |
        cd ~/kernel
        SUSFS_BRANCH="gki-android13-5.15"
        echo "Using branch for SUSFS: $SUSFS_BRANCH"
        git clone https://github.com/ShirkNeko/susfs4ksu.git -b "$SUSFS_BRANCH"
        git clone https://github.com/ShirkNeko/SukiSU_patch.git
        
        echo "==> Cloning Clang toolchain..."
        # 使用浅克隆并立即清理
        git clone --depth=1 --single-branch \
          https://github.com/inferno0230/clang.git clang-toolchain
        
        # 立即删除 .git 目录节省空间
        rm -rf clang-toolchain/.git
        
        echo "==> Clang toolchain size:"
        du -sh clang-toolchain
        
    - name: Clone kernel sources
      run: |
        cd ~/kernel

        # 设置 git 配置避免警告
        git config --global advice.detachedHead false
        git config --global init.defaultBranch main

        echo "==> Shallow fetch specific commit..."
        git init sm8550
        cd sm8550
        git remote add origin https://github.com/AlphaDroid-devices/kernel_oneplus_sm8550.git
        git fetch --depth=1 origin b76e7db1ea0f18b661e0973b43c06a74941e41bf
        git checkout FETCH_HEAD
        cd ..
        rm -rf sm8550/.git
        git clone https://github.com/as854437467/patch.git
        cp patch/hooks.c sm8550/security/selinux/hooks.c
        cp patch/input.c sm8550/drivers/input/input.c
        cp patch/open.c sm8550/fs/open.c
        cp patch/exec.c sm8550/fs/exec.c
        cp patch/read_write.c sm8550/fs/read_write.c
        cp patch/stat.c sm8550/fs/stat.c
        
        echo "==> Cloning modules source (2/3)..."
        git clone --depth=1 --single-branch --no-tags \
          https://github.com/AlphaDroid-devices/kernel_oneplus_sm8550-modules.git sm8550-modules
        rm -rf sm8550-modules/.git
        
        echo "==> Cloning devicetrees source (3/3)..."
        git clone --depth=1 --single-branch --no-tags \
          https://github.com/AlphaDroid-devices/kernel_oneplus_sm8550-devicetrees.git sm8550-devicetrees
        rm -rf sm8550-devicetrees/.git
        
        git clone --depth=1 https://github.com/ProjectInfinity-X/kernel_configs.git rom-configs
        cat "rom-configs/t/android-5.15/android-base.config" \
        >> "sm8550/kernel/configs/android-base.config"
        rm -rf rom-configs/.git
        
        echo "==> Source code sizes:"
        du -sh sm8550*
        echo "==> Total disk usage:"
        df -h
        
    - name: Add KernelSU-SukiSU Ultra
      run: |
        cd ~/kernel/sm8550
        echo "==> Adding SukiSU Ultra..."
        curl -LSs "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/main/kernel/setup.sh" | bash -s susfs-main

    - name: Apply Patches
      run: |
        cd ~/kernel
        cd sm8550
        echo "==> Applying SUSFS patch..."
        # Based on default android13-5.15
        cp ../susfs4ksu/kernel_patches/50_add_susfs_in_gki-android13-5.15.patch ./
        cp -r ../susfs4ksu/kernel_patches/fs/* ./fs/
        cp -r ../susfs4ksu/kernel_patches/include/linux/* ./include/linux/
        patch -p1 --fuzz=3 < 50_add_susfs_in_gki-android13-5.15.patch || true

        echo "==> Applying VFS patch..."
        cp ../SukiSU_patch/hooks/syscall_hooks.patch ./
        patch -p1 -F 3 < syscall_hooks.patch
        
        cp -r ../SukiSU_patch/other/zram/lz4k/include/linux/* ./include/linux/
        cp -r ../SukiSU_patch/other/zram/lz4k/lib/* ./lib/
        cp -r ../SukiSU_patch/other/zram/lz4k/crypto/* ./crypto/
        cp -r ../SukiSU_patch/other/zram/lz4k_oplus ./lib/
        cp ../SukiSU_patch/other/zram/zram_patch/5.15/lz4kd.patch ./
        echo "正在打lz4kd补丁"
        patch -p1 -F 3 < lz4kd.patch || true
        echo '完成LZ4KD补丁'

        cp ../SukiSU_patch/other/zram/zram_patch/5.15/lz4k_oplus.patch ./
        echo "正在打lz4k_oplus补丁"
        patch -p1 -F 3 < lz4k_oplus.patch || true
        echo '完成lz4k_oplus补丁'
        
        echo "==> Applying Hide Stuff patch..."
        cp ../SukiSU_patch/69_hide_stuff.patch ./
        patch -p1 -F 3 < 69_hide_stuff.patch


        
        echo "==> Patches applied."
    - name: Setup build environment variables
      run: |
        cd ~/kernel
        
        # 设置环境变量
        echo "PATH=$HOME/kernel/clang-toolchain/bin:$PATH" >> $GITHUB_ENV
        echo "ARCH=arm64" >> $GITHUB_ENV
        echo "SUBARCH=arm64" >> $GITHUB_ENV
        echo "CLANG_TRIPLE=aarch64-linux-gnu-" >> $GITHUB_ENV
        echo "CROSS_COMPILE=aarch64-linux-gnu-" >> $GITHUB_ENV
        echo "CROSS_COMPILE_COMPAT=arm-linux-gnueabi-" >> $GITHUB_ENV
        
        # 验证工具链
        echo "==> Verifying toolchain:"
        $HOME/kernel/clang-toolchain/bin/clang --version
        
    - name: Configure kernel
      run: |
        cd ~/kernel
        
        KERNEL_SOURCE_DIR="$HOME/kernel/sm8550"
        OUTPUT_DIR="$HOME/kernel/out"
        
        # 创建输出目录
        mkdir -p "$OUTPUT_DIR"
        
        echo "==> Disk usage before configuration:"
        df -h
        
        # Make 参数
        KBUILD_ARGS=(
          "LLVM=1"
          "LLVM_IAS=1"
          "CC=clang"
        )
        
        # 配置文件列表
        DEFCONFIG_FILES="gki_defconfig vendor/kalama_GKI.config vendor/oplus/kalama_GKI.config vendor/debugfs.config vendor/oplus/aston.config"
        
        echo "==> Merging configuration files..."
        make -C "${KERNEL_SOURCE_DIR}" O="${OUTPUT_DIR}" "${KBUILD_ARGS[@]}" $DEFCONFIG_FILES
        
        echo "==> Adding SukiSU configurations..."
        CONFIG_FILE="${OUTPUT_DIR}/.config"
        sed -i 's/^CONFIG_KPROBES=y$/# CONFIG_KPROBES is not set/' "${OUTPUT_DIR}/.config"
        if ! grep -q '^# CONFIG_KPROBES is not set' "${OUTPUT_DIR}/.config"; then
          echo '# CONFIG_KPROBES is not set' >> "${OUTPUT_DIR}/.config"
        fi

        # sed -i 's/CONFIG_MODULE_SIG=y/CONFIG_MODULE_SIG=n/g' "$CONFIG_FILE"
        echo "CONFIG_ZSMALLOC=y" >> "$CONFIG_FILE"
        sed -i 's/CONFIG_ZRAM=m/CONFIG_ZRAM=y/g' "$CONFIG_FILE"
        echo "CONFIG_CRYPTO_LZ4HC=y" >> "$CONFIG_FILE"
        echo "CONFIG_CRYPTO_LZ4K=y" >> "$CONFIG_FILE"
        echo "CONFIG_CRYPTO_LZ4KD=y" >> "$CONFIG_FILE"
        echo "CONFIG_CRYPTO_842=y" >> "$CONFIG_FILE"
        echo "CONFIG_CRYPTO_LZ4K_OPLUS=y" >> "$CONFIG_FILE"
        echo "CONFIG_ZRAM_WRITEBACK=y" >> "$CONFIG_FILE"
        echo "CONFIG_DEFAULT_BBR=y" >> "$CONFIG_FILE"
        echo "Adding configuration settings to gki_defconfig..."
        echo "CONFIG_KSU=y" >> "$CONFIG_FILE"
        echo "CONFIG_KPM=y" >> "$CONFIG_FILE"
        echo "CONFIG_KSU_SUSFS_SUS_SU=n" >> "$CONFIG_FILE"
        echo "CONFIG_KSU_MANUAL_HOOK=y" >> "$CONFIG_FILE"
        echo "CONFIG_TMPFS_XATTR=y" >> "$CONFIG_FILE"
        echo "CONFIG_TMPFS_POSIX_ACL=y" >> "$CONFIG_FILE"
        echo "CONFIG_IP_NF_TARGET_TTL=y" >> "$CONFIG_FILE"
        echo "CONFIG_IP6_NF_TARGET_HL=y" >> "$CONFIG_FILE"
        echo "CONFIG_IP6_NF_MATCH_HL=y" >> "$CONFIG_FILE"
        echo "CONFIG_TCP_CONG_ADVANCED=y" >> "$CONFIG_FILE"
        echo "CONFIG_TCP_CONG_BBR=y" >> "$CONFIG_FILE"
        echo "CONFIG_NET_SCH_FQ=y" >> "$CONFIG_FILE"
        echo "CONFIG_TCP_CONG_BIC=n" >> "$CONFIG_FILE"
        echo "CONFIG_TCP_CONG_WESTWOOD=n" >> "$CONFIG_FILE"
        echo "CONFIG_TCP_CONG_HTCP=n" >> "$CONFIG_FILE"
        echo "CONFIG_KSU_SUSFS=y" >> "$CONFIG_FILE"
        echo "CONFIG_KSU_SUSFS_HAS_MAGIC_MOUNT=y" >> "$CONFIG_FILE"
        echo "CONFIG_KSU_SUSFS_SUS_PATH=y" >> "$CONFIG_FILE"
        echo "CONFIG_KSU_SUSFS_SUS_MOUNT=y" >> "$CONFIG_FILE"
        echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_KSU_DEFAULT_MOUNT=y" >> "$CONFIG_FILE"
        echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_BIND_MOUNT=y" >> "$CONFIG_FILE"
        echo "CONFIG_KSU_SUSFS_SUS_KSTAT=y" >> "$CONFIG_FILE"
        echo "CONFIG_KSU_SUSFS_SUS_OVERLAYFS=n" >> "$CONFIG_FILE"
        echo "CONFIG_KSU_SUSFS_TRY_UMOUNT=y" >> "$CONFIG_FILE"
        echo "CONFIG_KSU_SUSFS_AUTO_ADD_TRY_UMOUNT_FOR_BIND_MOUNT=y" >> "$CONFIG_FILE"
        echo "CONFIG_KSU_SUSFS_SPOOF_UNAME=y" >> "$CONFIG_FILE"
        echo "CONFIG_KSU_SUSFS_ENABLE_LOG=y" >> "$CONFIG_FILE"
        echo "CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=y" >> "$CONFIG_FILE"
        echo "CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG=y" >> "$CONFIG_FILE"
        echo "CONFIG_KSU_SUSFS_OPEN_REDIRECT=y" >> "$CONFIG_FILE"
        
        
        # 应用最终配置
        make -C "${KERNEL_SOURCE_DIR}" O="${OUTPUT_DIR}" "${KBUILD_ARGS[@]}" olddefconfig
        echo "==> Configuration completed"
        
    - name: Build kernel
      run: |
        cd ~/kernel
        
        KERNEL_SOURCE_DIR="$HOME/kernel/sm8550"
        OUTPUT_DIR="$HOME/kernel/out"
        
        echo "==> Starting kernel build..."
        echo "==> Using 2 parallel jobs to conserve memory"
        
        # 构建内核 (使用较少的并行任务以节省内存)
        make -C "${KERNEL_SOURCE_DIR}" O="${OUTPUT_DIR}" -j2 \
          LLVM=1 LLVM_IAS=1 CC=clang
        
        echo "==> Kernel build completed!"
        
        # 验证关键文件
        KERNEL_IMAGE="$OUTPUT_DIR/arch/arm64/boot/Image"
        if [ ! -f "$KERNEL_IMAGE" ]; then
          echo "ERROR: Kernel Image not found at $KERNEL_IMAGE"
          exit 1
        fi
        
        echo "==> Kernel Image size: $(du -h "$KERNEL_IMAGE" | cut -f1)"
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: oneplus_sm8550
        path: $OUTPUT_DIR/arch/arm64/boot/Image
